### ISSUE TITLE
Colorblindness-friendlness on training curriculum page (for discussion)

### ISSUE THREAD

**Issue by wdconinc** [HSF/hsf.github.io#1073]
The colors on the [training curriculum page](https://hepsoftwarefoundation.org/training/curriculum.html) are close together in intensity, and use a color scheme that is not very suitable to people with colorblindness. Although the same information is already present in the text (Status: Early development, Status: Beta testing), it may make sense to adopt a visual cue that is independent of color as well.

I played around a bit with repeating gradients to achieve this within the existing color scheme, and came up with this:
![image](https://user-images.githubusercontent.com/4656391/153897856-0244a34e-0129-445a-a3f5-c20b13986d49.png)

The additional modality is the fraction of the rectangle that is filled by foreground color. The 45 degree angled stripes are to hint at e.g. police caution tape.

Here is the relevant css ([browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-linear-gradient()#browser_compatibility)):
```css
.tm-alpha {
  background-image: repeating-linear-gradient(-45deg, transparent, transparent 20px, #f9f2f4 20px, #f9f2f4 40px);
}
.tm-beta {
  background-image: repeating-linear-gradient(-45deg, transparent, transparent 10px, #f9f9f1 10px, #f9f9f1 40px);
}
```

I feel that this now distracts a bit too much, but I think a similar approach limited to the border of the rectangles could be effective without adding too much visual clutter.
